// <auto-generated />
using CoreWpfApp.AppDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreWpfApp.Migrations
{
    [DbContext(typeof(projectappdbContext))]
    [Migration("20200921192322_plusRegulations")]
    partial class plusRegulations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreWpfApp.AppDB.Pril11RegionIdHcpCvCs", b =>
                {
                    b.Property<string>("RegionName")
                        .HasColumnName("regionName")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<decimal>("CS")
                        .HasColumnName("c_s")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("CV")
                        .HasColumnName("c_v")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("Havg")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("ReionId")
                        .HasColumnName("reionId")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("RegionName")
                        .HasName("PRIMARY");

                    b.ToTable("pril11_region_id_hcp_cv_cs");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Pril2NPlessPaboveMrGamma", b =>
                {
                    b.Property<string>("Region")
                        .HasColumnName("region")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<decimal>("Gamma")
                        .HasColumnName("gamma")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("Mr")
                        .HasColumnName("mr")
                        .HasColumnType("int");

                    b.Property<decimal>("NPabove1")
                        .HasColumnName("n_pabove1")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("NPless1")
                        .HasColumnName("n_pless1")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Region")
                        .HasName("PRIMARY");

                    b.ToTable("pril2_n_pless_pabove_mr_gamma");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Regulations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RegCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RegLink")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RegName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Regulations");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table10ZiPsyi", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<decimal>("PsyI")
                        .HasColumnName("psy_i")
                        .HasColumnType("decimal(7,3)");

                    b.Property<decimal>("ZI")
                        .HasColumnName("z_i")
                        .HasColumnType("decimal(7,3)");

                    b.HasKey("Name")
                        .HasName("PRIMARY");

                    b.ToTable("table10_zi_psyi");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table11ZiVodonepronitsaemie", b =>
                {
                    b.Property<int>("A")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("a")
                        .HasColumnType("int");

                    b.Property<decimal>("NAbove065")
                        .HasColumnName("nAbove065")
                        .HasColumnType("decimal(7,3)");

                    b.Property<decimal>("NLess065")
                        .HasColumnName("nLess065")
                        .HasColumnType("decimal(7,3)");

                    b.HasKey("A")
                        .HasName("PRIMARY");

                    b.ToTable("table11_zi_vodonepronitsaemie");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table12SloyTalikhVod", b =>
                {
                    b.Property<int>("ClimateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("climateId")
                        .HasColumnType("int");

                    b.Property<decimal>("P0022")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P0033")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P005")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P010")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P015")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P045")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P095")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P328")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P495")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("P995")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ClimateId")
                        .HasName("PRIMARY");

                    b.ToTable("table12_sloy_talikh_vod");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table13RTau", b =>
                {
                    b.Property<decimal>("C")
                        .HasColumnName("c")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("Tau")
                        .HasColumnName("tau")
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("C")
                        .HasName("PRIMARY");

                    b.ToTable("table13_r_tau");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table14HPlim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HRain")
                        .IsRequired()
                        .HasColumnName("h_rain")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<decimal>("Plim")
                        .HasColumnType("decimal(7,3)");

                    b.HasKey("Id");

                    b.ToTable("table14_h_plim");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table15K1PlimCN", b =>
                {
                    b.Property<decimal>("Plim")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C085nAbove07")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C085nLess07")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C100nAbove07")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C100nLess07")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C120nAbove07")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C120nLess07")
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Plim")
                        .HasName("PRIMARY");

                    b.ToTable("table15_k1_plim_c_n");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table16K2PlimC", b =>
                {
                    b.Property<decimal>("P")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C085")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C100")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("C120")
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("P")
                        .HasName("PRIMARY");

                    b.ToTable("table16_k2_plim_c");
                });

            modelBuilder.Entity("CoreWpfApp.AppDB.Table9K", b =>
                {
                    b.Property<int>("F")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("K")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("F")
                        .HasName("PRIMARY");

                    b.ToTable("table_9_k");
                });
#pragma warning restore 612, 618
        }
    }
}
